name: comment-issue
run-name: comment-issue
on:
  issues:
    types: [opened]
jobs:
  comment-on-issue-action:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number  }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-on-issue-with-cli:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
