name: call-test-action
on:
  push:

jobs:
  outputs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: yashrajdighe/github-actions-learnings/actions/test@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
