name: call-test-action
on:
  pull_request:
    branches: [main]
jobs:
  outputs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: yashrajdighe/github-actions-learnings/actions/test@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
