name: slack-notification-workflow

on:
  workflow_dispatch:

concurrency:
  group: terraform
  cancel-in-progress: false

jobs:
  send-test-notification-using-bot-token:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel using message
        id: slack-message
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: '${{ secrets.SLACK_NOTIFICATION_CHANNEL_ID }}'
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post to a Slack channel using payload
        id: slack-payload
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: '${{ secrets.SLACK_NOTIFICATION_CHANNEL_ID }}'
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
