name: Create Infrastructure

on:
  pull_request:
    types: [opened, labeled]

jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for label
        id: check_label
        run: |
          PR_LABELS=$(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH)
          echo "Labels: $PR_LABELS"
          if echo "$PR_LABELS" | grep -q "create_infra"; then
            echo "Label 'create_infra' found."
            echo "::set-output name=label_found::true"
            echo "SKIP_JOB=false" >> $GITHUB_ENV
          else
            echo "Label 'create_infra' not found."
            echo "::set-output name=label_found::false"
            echo "SKIP_JOB=true" >> $GITHUB_ENV
          fi

  create_infrastructure: # should run only if a pull_request is opened or reopened with label create_infra
    needs: check_label
    runs-on: ubuntu-latest
    if: ${env.SKIP_JOB} == "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
