name: Yamllint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        python-version: 3.13.0
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@55aad42e4674b58b2b2fb7d8e7552402d922b4e7 #v5.3.0
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user yamllint
    - name: Analysing the code with pylint
      run: |
        yamllint $(git ls-files '*.yaml' '*.yml')
